#!/usr/bin/env python3
"""Guild adapter generator — the deterministic sync/generation command for
turning canonical `.guild/core/agents/` and `.guild/core/skills/`
definitions into provider-specific adapter files, per GUILD_MASTER_SPEC.md
section 12.

`.guild/core/` is always the source of truth. This script never reads from,
and never needs to read, the generated output to decide what to produce —
output is derived purely from canonical sources, so there is nothing to
keep in sync by hand.

Generates, rooted at --target (default: the current repository):
  - .agents/skills/<skill-id>/SKILL.md   Codex repository skills
  - .claude/agents/<profile-id>.md       Claude Code project subagents
  - .claude/skills/<skill-id>/SKILL.md   Claude Code project skills
  - .claude/settings.json                one deterministic, policy-derived
                                          permission rule (force-push deny)
  - a managed block appended into AGENTS.md and CLAUDE.md at the target
    root, without touching any existing repository-specific content

Usage:
    python3 .guild/core/adapters/generate_adapters.py [--target PATH]
    python3 .guild/core/adapters/generate_adapters.py [--target PATH] --check

--check performs drift detection: it computes what generation would produce
and compares it against what's on disk, without writing anything. Exit code
is 0 when nothing would change, 1 otherwise.
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
CORE_ROOT = SCRIPT_DIR.parent  # .guild/core/

GENERATED_MARKER = "GENERATED FILE — DO NOT EDIT BY HAND."
BLOCK_START = "<!-- guild:adapter:start -->"
BLOCK_END = "<!-- guild:adapter:end -->"

# Maps an agent-manifest `allowed_capabilities` entry to the Claude Code
# tools it implies. Deliberately coarse and deliberately never "*" — see
# "No unrestricted tool permissions by default" in bootstrap-prompts/04.
CAP_TOOLS = {
    "read_repository": ["Read"],
    "search_code": ["Grep", "Glob"],
    "create_plans_and_artifacts": ["Write"],
    "run_non_destructive_checks": ["Bash"],
    "run_changes_in_ephemeral_environment": ["Bash"],
    "edit_code_in_branch": ["Edit", "Write"],
    "add_dependency": ["Bash"],
    "create_migration": ["Edit", "Write"],
    "modify_ci": ["Edit", "Write"],
    "create_pull_request": ["Bash"],
    "consolidate_verified_memory": ["Edit", "Write"],
    "prioritize_backlog": ["Edit", "Write"],
    # Writing this profile's own ownership claim and knowledge ledger under
    # .guild/state/knowledge/ (GUILD_MASTER_SPEC.md section 7). This is why the
    # QA and security profiles get Write despite owning no product code: a
    # profile that cannot record what it learned cannot own an area. The
    # boundary that keeps them out of product code is their manifest's
    # forbidden_capabilities (edit_product_code, edit_code_in_branch), enforced
    # by check_independent_gates.py — not the coarse tool grant.
    "record_own_knowledge": ["Write"],
    "maintain_ownership_map": ["Edit", "Write"],
    "present_decision_request": ["Edit", "Write"],
}
TOOL_ORDER = ["Read", "Grep", "Glob", "Edit", "Write", "Bash"]

# The one deterministic, policy-derived Bash pattern generated by default.
# Most of .guild/core/policies/default-policies.yaml's approval_required actions
# (deploy_production, modify_production_data, ...) cannot be reliably
# pattern-matched from arbitrary shell commands across arbitrary target
# repos without guessing project- or language-specific tooling, so they
# stay enforced by the explicit human-approval workflow steps instead.
# Force-push is the one universal, unambiguous case.
GUILD_MANAGED_DENY = ["Bash(git push --force*)", "Bash(git push -f*)"]

# The `human` sentinel used by workflow steps and skills; not a profile, has no alias.
HUMAN = "human"


def source_header(source_path: str) -> str:
    return (
        f"<!-- {GENERATED_MARKER}\n"
        f"     Source of truth: {source_path}\n"
        f"     Regenerate: python3 .guild/core/adapters/generate_adapters.py --target . -->\n"
    )


def load_dir(glob_pattern: str) -> dict[str, dict]:
    out = {}
    for path in sorted(CORE_ROOT.glob(glob_pattern)):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        out[data["id"]] = data
    return out


def bullets(items: list[str]) -> str:
    return "\n".join(f"- {i}" for i in items) if items else "- (none)"


def named(profile_id: str, roster: dict[str, str]) -> str:
    """Renders a profile the way a human reads it: alias first, canonical id in
    parentheses. See GUILD_MASTER_SPEC.md section 3.1 — the alias is the
    human-facing name, the id is the machine one."""
    if profile_id == HUMAN:
        return "the human"
    return f"{roster[profile_id]} ({profile_id})"


def derive_tools(agent: dict) -> list[str]:
    tools = set()
    for cap in agent["allowed_capabilities"]:
        tools.update(CAP_TOOLS.get(cap, []))
    return [t for t in TOOL_ORDER if t in tools]


# ---------------------------------------------------------------- renderers

def render_codex_skill(skill: dict, roster: dict[str, str]) -> str:
    return f"""{source_header(f".guild/core/skills/{skill['id']}/SKILL.yaml (schema guild.skill-manifest/v1)")}
# {skill['name']}

*Canonical Guild skill id: `{skill['id']}`*

## Goal

{skill['goal']}

## Applicable profiles

{', '.join(named(p, roster) for p in skill['applicable_profiles'])}

## Inputs

{bullets(skill['inputs'])}

## Outputs

{bullets(skill['outputs'])}

## Steps

{bullets(skill['steps'])}
"""


def render_claude_skill(skill: dict, roster: dict[str, str]) -> str:
    return f"""---
name: {skill['id']}
description: {skill['goal']}
---

{source_header(f".guild/core/skills/{skill['id']}/SKILL.yaml (schema guild.skill-manifest/v1)")}
# {skill['name']}

*Canonical Guild skill id: `{skill['id']}`*

## Applicable profiles

{', '.join(named(p, roster) for p in skill['applicable_profiles'])}

## Inputs

{bullets(skill['inputs'])}

## Outputs

{bullets(skill['outputs'])}

## Steps

{bullets(skill['steps'])}
"""


def render_claude_agent(agent: dict, roster: dict[str, str]) -> str:
    tools = derive_tools(agent)
    description = (
        f"{agent['alias']} — {agent['mission']} Use this subagent for workflow "
        f"steps whose responsible_profile is `{agent['id']}`."
    )
    others = sorted(a for i, a in roster.items() if i != agent["id"])
    alias_note = (
        f"You are \"{agent['alias']}\" to the person you are working with, and "
        f"`{agent['id']}` to every machine that reads a manifest, a workflow field or an "
        f"artifact. Open anything a human reads — a question, an escalation, an approval "
        f"request, a handoff summary, a finished result — with your alias: "
        f"\"{agent['alias']} ({agent['id']}) — ...\" on first mention, then plain "
        f"\"{agent['alias']}\". Name the other profiles the same way: "
        f"{', '.join(others)}. Never hand a person a bare canonical id, and never write an "
        f"alias into an artifact field. See .guild/core/spec/GUILD_MASTER_SPEC.md section 3.1."
    )
    ledger_note = (
        f"Before doing a step's work, claim the area of the project it touches (skill "
        f"`claim-ownership`): confirm the area you already own in "
        f".guild/state/knowledge/ownership.yaml, or propose one with an explicit boundary, and read "
        f"your own ledger at .guild/state/knowledge/profiles/{agent['id']}.yaml for what you already "
        f"know about it. Work that falls in another profile's area goes back to the DM to route — two "
        f"owners for one part is a boundary error. After the work, append what the step actually "
        f"verified to that same ledger with evidence (skill `record-profile-knowledge`), record what "
        f"you could not resolve as an open question, and hand the DM the entry ids rather than a "
        f"retelling. Write only your own ledger: never another profile's, and never the ownership map "
        f"itself. See .guild/core/spec/GUILD_MASTER_SPEC.md section 7."
    )
    decision_note = (
        "When you hit something you cannot decide from the project itself — scope, naming, an "
        "ambiguity nobody owns — do not guess and do not leave it as a note. Raise it as an open "
        "question in your ledger blocked on the human, and hand it to the DM to put to a person as a "
        "decision request (skill `request-human-decision`): the question in plain terms, what it "
        "blocks, at least two options with consequences, your own recommendation, and the default "
        "that applies if nobody answers. Never act on a default the human has not been shown, and "
        "never let a run close with a decision it needed still unasked. Red-tier actions are not "
        "decision requests: they block on an explicit human approval and never carry a default. See "
        ".guild/core/spec/GUILD_MASTER_SPEC.md section 11.2."
    )
    gates_note = (
        "This profile can never approve its own QA or security result. Every Red-tier action "
        "(merge to a protected branch, production deployment, destructive migration, production "
        "data changes, secret or permission changes, payment behavior changes, external "
        "communications, material-cost provisioning) always requires a separate, explicit human "
        "approval step per .guild/core/policies/default-policies.yaml, regardless of the tools listed "
        "above."
    )
    return f"""---
name: {agent['id']}
description: {description}
tools: {', '.join(tools) if tools else '(none — read canonical files directly)'}
---

{source_header(f".guild/core/agents/{agent['id']}/manifest.yaml (schema guild.agent-manifest/v1)")}
You are the {agent['alias']} — {agent['name']} (Guild profile `{agent['id']}`).

## Mission

{agent['mission']}

## Speaking to the human

{alias_note}

## Owning your part and recording what you learn

{ledger_note}

## When you cannot decide it yourself

{decision_note}

## Responsibilities

{bullets(agent['responsibilities'])}

## Non-responsibilities

{bullets(agent['non_responsibilities'])}

## Required inputs

{bullets(agent['required_inputs'])}

## Produced outputs

{bullets(agent['produced_outputs'])}

## Forbidden actions

{gates_note}

Full forbidden-capabilities list: {', '.join(agent['forbidden_capabilities'])}.

## Quality gates

{bullets(agent['quality_gates'])}

## Escalation conditions

{bullets(agent['escalation_conditions'])}

## Collaboration & handoffs

{bullets(agent.get('collaboration', []))}
"""


def render_agents_md_block(agent_ids: list[str], skill_ids: list[str], roster: dict[str, str]) -> str:
    example_id = "quality-assurance-engineer"
    example = f"{roster[example_id]} ({example_id})" if example_id in roster else "Alias (profile-id)"
    addressing = textwrap.fill(
        "Each profile has a human-facing alias and a canonical id. Anything a person reads "
        "names the profile by alias — " + ", ".join(sorted(roster.values())) + " — with the "
        f"canonical id in parentheses on first mention (\"{example}\"). Artifact fields "
        "(`responsible_profile`, `evaluated_by`, `requested_by`, ...) keep canonical ids only. "
        "In single-assistant mode, announce every role switch by alias before starting that "
        "step's work. Red-tier actions reach the human as an approval request naming who is "
        "asking and who is blocked — see `.guild/core/spec/GUILD_MASTER_SPEC.md` sections 3.1 "
        "and 11.",
        width=88,
    )
    ownership = textwrap.fill(
        "Every part of the project has exactly one owning profile. A profile claims its area "
        "before working (`claim-ownership`) and appends what each interaction verified to its own "
        "ledger at `.guild/state/knowledge/profiles/<profile-id>.yaml` afterwards "
        "(`record-profile-knowledge`) — with evidence, never private reasoning. A profile writes "
        "only its own ledger. The orchestrator maintains `.guild/state/knowledge/ownership.yaml`, "
        "an index of area, owner, ledger location, newest entry and related areas: it routes by "
        "those pointers instead of holding what every owner knows. Handoffs carry ledger entry "
        "ids, not copies. See `.guild/core/spec/GUILD_MASTER_SPEC.md` section 7.",
        width=88,
        break_on_hyphens=False,
    )
    decisions = textwrap.fill(
        "A decision no profile can make from the project itself — scope, naming, licensing, an "
        "ambiguity nobody owns — is never resolved by assumption and never left as a note. It becomes "
        "a decision request in `.guild/state/planning/decisions/` stating what it blocks, at least two "
        "options with consequences, a recommendation, and the default that applies if nobody answers; "
        "the orchestrator presents it to a person and records the answer, or an explicit deferral. A "
        "default never applies before the human has been shown it, every open decision is listed by id "
        "in `PROJECT_STATUS.md`, and no run closes with a decision it needed left unasked. Red-tier "
        "actions are approvals, not decision requests: they block outright and never carry a default. "
        "See `.guild/core/spec/GUILD_MASTER_SPEC.md` section 11.2.",
        width=88,
        break_on_hyphens=False,
    )
    return f"""## Guild adapter (generated — do not edit this section by hand)

This project has [Guild](.guild/core/spec/GUILD_MASTER_SPEC.md) installed. `.guild/core/`
is the canonical source of truth; everything below is generated from it. This project's
own knowledge, planning and run history live in `.guild/state/`, untouched by Guild
upgrades.

- Codex skills: `.agents/skills/<skill-id>/SKILL.md` ({len(skill_ids)} skills)
- Claude Code subagents: `.claude/agents/<profile-id>.md` ({len(agent_ids)} profiles)
- Claude Code skills: `.claude/skills/<skill-id>/SKILL.md` ({len(skill_ids)} skills)
- Generic / single-assistant clients: read `.guild/core/agents/`, `.guild/core/skills/`
  and `.guild/core/workflows/` directly — see
  `.guild/core/workflows/EXECUTION_MODES.md` mode 1.

### Addressing the human

{addressing}

### Ownership and knowledge

{ownership}

### Pending decisions

{decisions}

Regenerate after any change under `.guild/core/agents/` or `.guild/core/skills/`:

    python3 .guild/core/adapters/generate_adapters.py --target .

Check for drift (fails if generated files no longer match canonical sources):

    python3 .guild/core/adapters/generate_adapters.py --target . --check
"""


def render_claude_md_block() -> str:
    return """## Guild adapter (generated — do not edit this section by hand)

Claude Code subagents are generated under `.claude/agents/<profile-id>.md` and Claude
Code skills under `.claude/skills/<skill-id>/SKILL.md`, both derived from the canonical
manifests under `.guild/core/agents/` and `.guild/core/skills/`. Quality assurance
(`quality-assurance-engineer` / Barbarian) and security (`product-security-engineer` /
Rogue) are separate subagents, independent from every implementation subagent, per
`.guild/core/spec/GUILD_MASTER_SPEC.md` principle 6.

Every subagent introduces itself to the human by its Guild alias (DM, Paladin, Fighter,
Druid, Bard, Ranger, Artificer, Wizard, Warlock, Barbarian, Rogue, Cleric, Sorcerer,
Monk) with its canonical id in parentheses on first mention, and names the other profiles
the same way; canonical ids alone stay in artifact fields, per
`.guild/core/spec/GUILD_MASTER_SPEC.md` section 3.1.

Each subagent owns a declared part of the project and keeps its own knowledge ledger
under `.guild/state/knowledge/profiles/<profile-id>.yaml`, claiming its area before a
step and recording what the step verified afterwards. The DM
(`workflow-knowledge-orchestrator`) maintains `.guild/state/knowledge/ownership.yaml`
as an index of area, owner and ledger location, and routes by those pointers — which
is what lets a subagent hand back entry ids instead of its whole reasoning, and keeps
the orchestrator's context bounded as the project grows.

Nothing is left pending by default: what a subagent cannot decide from the project
itself becomes a decision request under `.guild/state/planning/decisions/` — options,
a recommendation and the default that applies if nobody answers — which the DM puts to
a person and records. A default never applies before the human has seen it, and
Red-tier actions remain approvals that block outright.

No subagent is granted unrestricted tool access; each gets only the tools its
`allowed_capabilities` imply (see `.guild/core/adapters/generate_adapters.py`).
`.claude/settings.json` additionally denies one deterministic, policy-derived pattern
(force-push) as a concrete instance of "optional policy-derived hooks only when
deterministic enforcement is appropriate" — the rest of
`.guild/core/policies/default-policies.yaml`'s Red-tier actions cannot be reliably
pattern-matched from arbitrary shell commands and still rely on the explicit
human-approval workflow steps instead.

Regenerate after any change under `.guild/core/agents/` or `.guild/core/skills/`:

    python3 .guild/core/adapters/generate_adapters.py --target .
"""


def merge_managed_block(existing: str, block: str) -> str:
    full_block = f"{BLOCK_START}\n{block.strip()}\n{BLOCK_END}\n"
    if BLOCK_START in existing and BLOCK_END in existing:
        pre = existing.split(BLOCK_START)[0].rstrip("\n")
        post = existing.split(BLOCK_END)[1].lstrip("\n")
    else:
        pre = existing.rstrip("\n")
        post = ""
    parts = [p for p in (pre, full_block.rstrip("\n"), post) if p]
    return "\n\n".join(parts) + "\n"


def extract_managed_block(text: str) -> str | None:
    if BLOCK_START not in text or BLOCK_END not in text:
        return None
    return text.split(BLOCK_START)[1].split(BLOCK_END)[0].strip()


# ---------------------------------------------------------------- plan / apply

class Plan:
    """A set of (path -> desired text) writes and a set of directories to sync
    (deleting any stale generated file no longer backed by a canonical id)."""

    def __init__(self):
        self.files: dict[Path, str] = {}
        self.synced_dirs: dict[Path, set[str]] = {}  # dir -> set of expected child dir/file names

    def put(self, path: Path, content: str):
        self.files[path] = content

    def sync_dir(self, directory: Path, expected_names: set[str]):
        self.synced_dirs[directory] = expected_names


def build_plan(target: Path) -> Plan:
    agents = load_dir("agents/*/manifest.yaml")
    skills = load_dir("skills/*/SKILL.yaml")
    plan = Plan()

    codex_skills_dir = target / ".agents" / "skills"
    claude_skills_dir = target / ".claude" / "skills"
    claude_agents_dir = target / ".claude" / "agents"

    roster = {agent_id: agent["alias"] for agent_id, agent in agents.items()}

    for skill_id, skill in skills.items():
        plan.put(codex_skills_dir / skill_id / "SKILL.md", render_codex_skill(skill, roster))
        plan.put(claude_skills_dir / skill_id / "SKILL.md", render_claude_skill(skill, roster))
    plan.sync_dir(codex_skills_dir, set(skills))
    plan.sync_dir(claude_skills_dir, set(skills))

    for agent_id, agent in agents.items():
        plan.put(claude_agents_dir / f"{agent_id}.md", render_claude_agent(agent, roster))
    plan.sync_dir(claude_agents_dir, {f"{a}.md" for a in agents})

    agents_md = target / "AGENTS.md"
    claude_md = target / "CLAUDE.md"
    existing_agents_md = agents_md.read_text(encoding="utf-8") if agents_md.exists() else ""
    existing_claude_md = claude_md.read_text(encoding="utf-8") if claude_md.exists() else ""
    plan.put(agents_md, merge_managed_block(
        existing_agents_md, render_agents_md_block(sorted(agents), sorted(skills), roster)))
    plan.put(claude_md, merge_managed_block(existing_claude_md, render_claude_md_block()))

    return plan


def apply_plan(plan: Plan, target: Path) -> list[str]:
    changes = []
    for path, content in plan.files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        before = path.read_text(encoding="utf-8") if path.exists() else None
        if before != content:
            path.write_text(content, encoding="utf-8")
            changes.append(f"wrote {path}")

    for directory, expected in plan.synced_dirs.items():
        if not directory.exists():
            continue
        for child in sorted(directory.iterdir()):
            if child.name not in expected:
                if child.is_dir():
                    marker_file = child / "SKILL.md"
                else:
                    marker_file = child
                text = marker_file.read_text(encoding="utf-8") if marker_file.exists() else ""
                if GENERATED_MARKER in text:
                    if child.is_dir():
                        for f in child.iterdir():
                            f.unlink()
                        child.rmdir()
                    else:
                        child.unlink()
                    changes.append(f"removed orphaned {child}")

    changes.extend(apply_settings_json(target))
    return changes


def settings_json_path(target: Path) -> Path:
    return target / ".claude" / "settings.json"


def apply_settings_json(target: Path) -> list[str]:
    path = settings_json_path(target)
    data = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
    perms = data.setdefault("permissions", {})
    deny = perms.setdefault("deny", [])
    changed = False
    for pattern in GUILD_MANAGED_DENY:
        if pattern not in deny:
            deny.append(pattern)
            changed = True
    if changed or not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        return [f"wrote {path}"]
    return []


def check_plan(plan: Plan, target: Path) -> list[str]:
    diffs = []
    for path, content in plan.files.items():
        rel = path.relative_to(target)
        if path.name in ("AGENTS.md", "CLAUDE.md"):
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            want_block = extract_managed_block(content)
            have_block = extract_managed_block(current)
            if have_block != want_block:
                diffs.append(f"[managed-block-drift] {rel}: generated adapter section is out of date")
            continue
        if not path.exists():
            diffs.append(f"[missing] {rel}: not generated yet")
        elif path.read_text(encoding="utf-8") != content:
            diffs.append(f"[stale] {rel}: no longer matches its canonical source")

    for directory, expected in plan.synced_dirs.items():
        if not directory.exists():
            continue
        for child in sorted(directory.iterdir()):
            if child.name not in expected:
                diffs.append(f"[orphan] {child.relative_to(target)}: no longer backed by a canonical id")

    settings_path = settings_json_path(target)
    data = json.loads(settings_path.read_text(encoding="utf-8")) if settings_path.exists() else {}
    deny = data.get("permissions", {}).get("deny", [])
    for pattern in GUILD_MANAGED_DENY:
        if pattern not in deny:
            diffs.append(f"[missing-policy-rule] .claude/settings.json: missing deny rule '{pattern}'")

    return diffs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", default=".", help="Target repository root (default: current directory)")
    parser.add_argument("--check", action="store_true", help="Drift detection only; write nothing")
    args = parser.parse_args()

    target = Path(args.target).resolve()
    plan = build_plan(target)

    if args.check:
        diffs = check_plan(plan, target)
        if diffs:
            print(f"Adapter drift check against {target}:")
            for d in diffs:
                print(f"ERROR   {d}")
            print(f"\nFAILED with {len(diffs)} drift issue(s). Run without --check to regenerate.")
            return 1
        print(f"OK: generated adapters under {target} match canonical .guild/ sources.")
        return 0

    changes = apply_plan(plan, target)
    if changes:
        print(f"Generated adapters under {target}:")
        for c in changes:
            print(f"  {c}")
    else:
        print(f"Adapters under {target} already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
